services:
  - type: web
    name: bookmydesk
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run serve:ssr:bookmydesk
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
